dependencies:
  - name: ibm-open-liberty
    version: 1.9.0
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
  - name: ibm-mongodb-dev
    version: 1.1.3
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/