ibm-websphere-liberty:
  ###############################################################################
  # Licensed Materials - Property of IBM.
  # Copyright IBM Corporation 2017. All Rights Reserved.
  # U.S. Government Users Restricted Rights - Use, duplication or disclosure
  # restricted by GSA ADP Schedule Contract with IBM Corp.
  #
  # Contributors:
  #  IBM Corporation - initial API and implementation
  ###############################################################################


  ###############################################################################
  ## Common image variables
  ###############################################################################
  image:
    repository: acmeair-authservice-java
    tag: latest
    pullPolicy: Always
    license: ""

    readinessProbe: {}
    # Example:
    # readinessProbe:
    #   httpGet:
    #     path: /custom/app
    #     port: 9080
    #   initialDelaySeconds: 3
    #   periodSeconds: 5

    livenessProbe: {}
    # Example:
    # livenessProbe:
    #   httpGet:
    #     path: /custom/health
    #     port: 9080
    #   initialDelaySeconds: 40
    #   periodSeconds: 10

    extraEnvs: []
    # Example:
    # extraEnvs:
    # - name: FOO
    #   valueFrom:
    #     secretKeyRef:
    #       key: FOO
    #       name: secret-resource
    # - name: BAR
    #   value: bar

    lifecycle: {}
    # Example:
    # lifecycle:
    #   postStart:
    #     exec:
    #       command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
    #   preStop:
    #     exec:
    #       command: ["/usr/sbin/nginx","-s","quit"]

    serverOverridesConfigMapName: ""
    # Server Configuration Overrides
    # Example:
    # serverOverridesConfigMapName: "custom-server-configmap"

    extraVolumeMounts: []
    # Example:
    # extraVolumeMounts:
    #   - name: podinfo
    #     mountPath: /podinfo
    #     readOnly: false

    security: {}
    # Example:
    # security:
    #   securityContext:
    #     privileged: false
    #     readOnlyRootFilesystem: false
    #     allowPrivilegeEscalation: false
    #     capabilities:
    #       drop:
    #       - ALL

  resourceNameOverride: ""

  deployment:
    annotations: {}
    # Example:
    # annotations:
    #   prometheus.io/scheme: "http"
    #   prometheus.io/scrape: "true"

    labels: {}
    # Example:
    # labels:
    #   environment: "dev"
    #   tier: "backend"

  pod:
    annotations: {}
    # Example:
    # annotations:
    #   prometheus.io/scheme: "http"
    #   prometheus.io/scrape: "true"

    security: {}
    # Example:
    # security:
    #   hostNetwork: false
    #   hostPID: false
    #   hostIPC: false
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1001

    labels: {}
    # Example:
    # labels:
    #   environment: "dev"
    #   tier: "backend"

    extraInitContainers: []
    # Example:
    # extraInitContainers:
    # - name: init-myservice
    #   image: sys-loz-test-team-docker-local.artifactory.swg-devops.com/busybox
    #   command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']

    extraContainers: []
    # Example:
    # extraContainers:
    # - name: my-sidecar
    #  image: sys-loz-test-team-docker-local.artifactory.swg-devops.com/nginx:latest
    # - name: lemonldap-ng-controller
    #  image: lemonldapng/lemonldap-ng-controller:0.2.0
    #  args:
    #    - /lemonldap-ng-controller
    #    - --alsologtostderr
    #    - --configmap=$(POD_NAMESPACE)/lemonldap-ng-configuration
    #  env:
    #    - name: POD_NAME
    #      valueFrom:
    #        fieldRef:
    #          fieldPath: metadata.name
    #  volumeMounts:
    #  - name: copy-portal-skins
    #    mountPath: /srv/var/lib/lemonldap-ng/portal/skins

    extraVolumes: []
    # Example:
    # extraVolumes:
    #   - name: podinfo
    #     downwardAPI:
    #       items:
    #         - path: "labels"
    #           fieldRef:
    #             fieldPath: metadata.labels
    #         - path: "annotations"
    #           fieldRef:
    #             fieldPath: metadata.annotations

  service:
    enabled: true
    name: "acmeair-auth-service"
    port: 9080
    targetPort: 9080
    type: ClusterIP
    annotations: {}
    # Example:
    # annotations:
    #   prometheus.io/path: "/custom/metrics"
    #   prometheus.io/port: "9157"

    labels: {}
    # Example:
    # labels:
    #   environment: "dev"
    #   tier: "backend"

    extraPorts: []
    # Example:
    # extraPorts:
    #   - protocol: TCP
    #     port: 9444
    #     targetPort: 9444
    #     name: vhost-https

    extraSelectors: {}
    # Example:
    # extraSelectors:
    #   "environment": "dev"
    #   "tier": "backend"

  jmsService:
    enabled: false
    port: 7286
    targetPort: 7286
    type: NodePort

  iiopService:
    enabled: false
    nonSecurePort: 2809
    nonSecureTargetPort: 2809
    securePort: 9402
    secureTargetPort: 9402
    type: NodePort

  ssl:
    enabled: false
    useClusterSSLConfiguration: false
    createClusterSSLConfiguration: false

  ingress:
    enabled: true
    path: "/auth"
    rewriteTarget: "/auth"
    host: ""
    secretName: ""
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/connection-proxy-header: "keep-alive"

    labels: {}
    # Example:
    # labels:
    #   environment: "dev"
    #   tier: "backend"

  ###############################################################################
  ## Persistence Storage
  ###############################################################################

  ## Persistence is disabled by default, set Enabled: true to use
  persistence:
    name: "liberty-pvc"
    ## Tranlog requires a Persistence Storage volume size minimum of 1Gi
    size: "1Gi"

    useDynamicProvisioning: true

    fsGroupGid:

    ## Specify the name of the StorageClass
    ## Setting StorageClass: "" will use whatever storageClass is currently
    ## setup as the Default
    storageClassName: ""

    # if your not using dynamic provisioning, you can use selectors to
    # refine the binding process. You cannot specify a selector if your using dynamic provisioning!
    selector:
      label: ""
      value: ""

  ###############################################################################
  ## Logs
  ###############################################################################
  logs:
    persistLogs: false
    persistTransactionLogs: false
    consoleFormat: json
    consoleLogLevel: info
    consoleSource: message,trace,accessLog,ffdc

  ###############################################################################
  ## MicroProfile
  ###############################################################################
  microprofile:
    health:
      enabled: false

  ###############################################################################
  ## Monitoring
  ###############################################################################
  monitoring:
    enabled: false

  ###############################################################################
  ## Auto scaling
  ###############################################################################
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

  ###############################################################################
  ## Resource constraints
  ###############################################################################
  resources:
    constraints:
      enabled: false
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi

  ###############################################################################
  ## Architecture
  ###############################################################################
  # Specify architecture (amd64, ppc64le, s390x) and weight to be
  # used for scheduling as follows:
  #   0 - Do not use
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  arch:
    amd64: "3 - Most preferred"
    ppc64le: "0 - Do not use"
    s390x: "0 - Do not use"

  ###############################################################################
  ## Environmental variables
  ###############################################################################
  env:
    jvmArgs: "-DcustomerClient/mp-rest/url=http://acmeair-customer-service:9080/customer"

  ###############################################################################
  ## Session cache
  ###############################################################################
  sessioncache:
    hazelcast:
      enabled: false
      embedded: false
      image:
        repository: hazelcast/hazelcast
        tag: "3.10.6"
        pullPolicy: IfNotPresent

  ###############################################################################
  ## Role-Based Access Control
  ###############################################################################
  rbac:
    install: true

    
  ###############################################################################
  ## OpenID Connect
  ###############################################################################
  oidcClient:
    enabled: false
    clientId: ""
    clientSecretName: ""
    discoveryURL: ""



